[workspace]
resolver = "3"
members = ["crates/iced-cube", "crates/gallery"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sam-ruff/iced-cube"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(docsrs)"] }

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"

[profile.release-wasm]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
